auto: true

#markdown: rdiscount
highlighter: 'rouge'
#paginate: 8
permalink: /:title
title: Sylvanas
url: http://aizonzzz.github.io
feed: /atom.xml
author_info: <a href="http://aizonzzz.github.io/">Aizon</a>
